apiVersion: v2
name: camunda-platform
version: 8.1.4
appVersion: 8.1.x
description: |
  Camunda Platform 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Camunda Platform charts.
  - name: connectors
    version: 0.15.0
    condition: "connectors.enabled"
  - name: identity
    version: 8.1.4
    condition: "identity.enabled"
    import-values:
      # NOTE: This is used to share Identity image details with its subchart Keycloak.
      #       It should be part of Identity but Helm 3 missing this option currently (v3.10.x).
      # TODO: Move this to Identity subchart once "export-values" is implemented.
      #       https://github.com/helm/helm/pull/10804
      - child: image
        parent: global.identity.image
      # NOTE: This is used to share the port of the Identity service with the web-modeler subchart
      - child: service
        parent: global.identity.service
  - name: operate
    version: 8.1.4
    condition: "operate.enabled"
  - name: optimize
    version: 8.1.4
    condition: "optimize.enabled"
  - name: tasklist
    version: 8.1.4
    condition: "tasklist.enabled"
  - name: web-modeler
    version: 8.1.4
    condition: "web-modeler.enabled"
  - name: zeebe
    version: 8.1.4
    condition: "zeebe.enabled"
  - name: zeebe-gateway
    version: 8.1.4
    condition: "zeebe.enabled"
  # Dependency charts.
  - name: elasticsearch
    repository: "https://helm.elastic.co"
    version: 7.17.1
    condition: "elasticsearch.enabled"
  # Helpers charts.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Camunda Platform 8 docs
      url: https://docs.camunda.io/
    - name: Camunda Platform 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda Platform 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "support startupProbe, readinessProbe, and livenessProbe"
    - kind: changed
      description: "add operate default actuator endpoints"
    - kind: changed
      description: "add tasklist default actuator endpoints"
