kind: ConfigMap
metadata:
  name: {{ include "connectors.fullname" . }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
apiVersion: v1
data:
  application.yml: |
    # Connectors configuration file
    camunda.connectors:
      ### TODO: add Operate API dependency for Inbound connectors
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: "{{ tpl .Values.global.zeebeClusterName . }}-gateway:{{ .Values.global.zeebePort }}"
    logging:
{{- with .Values.logging }}
{{ . | toYaml | indent 6 }}
{{- end }}
    #Spring Boot Actuator endpoints to be exposed
    management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus
